Adding check outliers
impact-initiatives/cleaningtools pull request #11
Opened 2023-03-22 09:14 UTC by mhkhan27

2023-03-22 17:18 UTC, mhkhan27 commented
![](https://github.trello.services/images/mini-trello-icon.png) [check for outliers](https://trello.com/c/J5opO5SE/133-check-for-outliers)

2023-03-23 16:19 UTC, yannsay-impact requested changes

2023-03-23 16:19 UTC, yannsay-impact commented on R/check_outliers.R
> +                              minumum_unique_value_of_variable =NULL,
typo in minumum

2023-03-23 16:19 UTC, yannsay-impact commented on tests/testthat/test-check_outliers.R
> +
not sure what line 30 to 34 are about. You are checking that the outliers from the IQR definition are present in the log but this is not what you are actually calculating. While the 3 values from boxplot_outlier_age are present, the outliers5 has 11 values for age.

2023-03-23 17:20 UTC, mhkhan27 commented on tests/testthat/test-check_outliers.R
> +
Not sure! I am not having NAs as outliers.

2023-03-23 18:13 UTC, mhkhan27 commented on R/check_outliers.R
> +      pivot_longer(cols = paste0(x),names_to ="question",values_to= "old_value")
Lets keep **question** and **old_value**

2023-03-30 09:43 UTC, merged